version: '3.8'

services:
  web:
    build: .
    image: zolin17/big-data:latest
    container_name: big-data
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
